{
 "title": "Dishy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "slowest_ping",
    "query": {
     "query": "query_result(topk(5, avg_over_time(wifi_ping_report_latency_ms[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(dish_uplink_throughput_bps[7d:10m])/(1000*1000)",
     "legendFormat": "Peak Uplink (Mbps)"
    },
    {
     "expr": "max_over_time(dish_downlink_throughput_bps[7d:10m])/(1000*1000)",
     "legendFormat": "Peak Downlink (Mbps)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(speedtest_up[7d:10m])",
     "legendFormat": "Best Speedtest Best Up (Mbps, 7d)"
    },
    {
     "expr": "max_over_time(speedtest_down[7d:10m])",
     "legendFormat": "Speedtest Best Down (Mbps, 7d)"
    },
    {
     "expr": "min_over_time(speedtest_latency[7d:10m])",
     "legendFormat": "Speedtest Best Latency (ms, 7d)"
    }
   ]
  },
  {
   "title": "Dish Software Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dish_device_info", "legendFormat": "{{software_version}}" }
   ]
  },
  {
   "title": "Uplink",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(dish_uplink_throughput_bps[60m]) / (1000*1000)",
     "legendFormat": "Dishy (Mbps)"
    }
   ]
  },
  {
   "title": "Ping by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service) (rate(wifi_ping_report_latency_ms[5m])) > 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downlink",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(dish_downlink_throughput_bps[60m]) / (1000*1000)",
     "legendFormat": "Dishy (Mbps)"
    }
   ]
  },
  {
   "title": "Top 5 Highest Pings",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "wifi_ping_report_latency_ms{location=~\"$slowest_ping\"}",
     "legendFormat": "{{service}} - {{location}}"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "description": "Compares your latency to global recorded latency",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(wifi_ping_report_latency_ms[60m]))",
     "legendFormat": "Dishy (ms)"
    }
   ]
  }
 ]
}