apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: $PROMETHEUS_URL
    isDefault: true
    jsonData:
      httpMethod: GET
  
  - name: SpaceXApi
    type: JSON API
    access: proxy
    url: "https://api.spacexdata.com/v4"

  - name: Netstats
    type: influxdb
    access: proxy
    database: netstats
    user: $INFLUXDB_USERNAME
    password: $INFLUXDB_PASSWORD
    url: $INFLUXDB_URL
    jsonData:
      httpMode: GET

  - name: Starlinkstats
    type: influxdb
    access: proxy
    database: starlinkstats
    user: $INFLUXDB_USERNAME
    password: $INFLUXDB_PASSWORD
    url: $INFLUXDB_URL
    jsonData:
      httpMode: GET
