global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
          - "prometheus:9090"

  - job_name: "node-exporter"
    static_configs:
      - targets: 
          - "host.docker.internal:9100"

  - job_name: "starlink-exporter"
    scrape_interval: 3s
    scrape_timeout: 3s
    static_configs:
      - targets: 
          - "starlink-exporter:9817"

  - job_name: "speedtest-exporter"
    scrape_interval: 1h
    scrape_timeout: 1m
    static_configs:
      - targets: 
          - "speedtest-exporter:9798"
