{
 "title": "Starlink Monitoring Dashboard Local",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "License working(Hours)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_valid_seconds" }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "starlink_dish_pop_ping_latency_seconds{instance=\"starlink-exporter:9817\", job=\"starlink-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Azimuth degrees",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "starlink_dish_bore_sight_azimuth_deg",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elevation degrees",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "starlink_dish_bore_sight_elevation_deg{instance=\"starlink-exporter:9817\", job=\"starlink-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Speed (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "starlink_dish_downlink_throughput_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upload Speed (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "starlink_dish_uplink_throughput_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}